apiVersion: v1
items:
- apiVersion: awx.ansible.com/v1beta1
  kind: AWX
  metadata:
    labels:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/operator-version: ""
      app.kubernetes.io/part-of: awx
      something: yoloswag
    name: awx
    namespace: upgrade
  spec:
    task_affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - awx-task
    web_affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - awx-web
    additional_labels:
    - something
    admin_email: admin@localhost
    admin_user: admin
    auto_upgrade: true
    create_preload_data: true
    development_mode: false
    garbage_collect_secrets: false
    image: ghcr.io/ansible/awx
    image_pull_policy: Always
    image_version: devel
    ingress_type: route
    ipv6_disabled: false
    loadbalancer_ip: ""
    loadbalancer_port: 80
    loadbalancer_protocol: http
    no_log: true
    postgres_configuration_secret: awx-postgres-configuration
    projects_persistence: false
    projects_storage_access_mode: ReadWriteMany
    projects_storage_size: 8Gi
    replicas: 2
    route_tls_termination_mechanism: Edge
    set_self_labels: true
    task_privileged: false
    termination_grace_period_seconds: 300
kind: List
metadata:
  resourceVersion: ""
