apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/operator-version: ""
    app.kubernetes.io/part-of: awx
  name: awx
  namespace: awx
spec:
  admin_email: admin@localhost
  admin_user: admin
  auto_upgrade: true
  create_preload_data: true
  development_mode: false
  garbage_collect_secrets: false
  image: ghcr.io/ansible/awx
  image_pull_policy: Always
  image_version: devel
  ingress_type: route
  ipv6_disabled: false
  loadbalancer_ip: ""
  loadbalancer_port: 80
  loadbalancer_protocol: http
  no_log: true
  postgres_configuration_secret: awx-postgres-configuration
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 3
  route_tls_termination_mechanism: Edge
  set_self_labels: true
  task_privileged: false
  termination_grace_period_seconds: 300
  task_affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - awx-task
          topologyKey: topology.kubernetes.io/zone
        weight: 100
  web_affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - awx-web
          topologyKey: topology.kubernetes.io/zone
        weight: 100
    ee_extra_env: |
      - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
        value: enabled
